#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Demo.Resource", IsApplication=true)]

namespace Demo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int verbose_indent = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int monkey1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monkey2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int monkey3 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int monkey4 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int monkey5 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int monkey6 = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int button_overdraw = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int button_verbose = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int monkeyMug = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int monkeyName = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int score = 2131034115;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int overdraw_row = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int verbose_layout = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] VerboseRelativeLayout = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int VerboseRelativeLayout_verbose_indent = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
